version: '3'
services:

  janustest:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    restart: always
    container_name: janustest
    volumes:
      - ./log/:/var/log/
    ports:
      - 7088:7088
      - 8088:8088
      - 8188:8188
      - 10000-10030:10000-10030/udp


  nginx_server:
    image: nginx:alpine
    restart: always
    ports:
      - 81:80
    volumes:
      - ./janus:/usr/share/nginx/html
      - ./nginxtest/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - janustest