services:
# 프록시 서버 설정
  proxy:
    depends_on:
      - nginx
      - fastapi
      - janus
    image: nginx:alpine
    container_name: proxyserver 
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxyserver/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot:/etc/letsencrypt
      - ./webpage/index.html:/usr/share/nginx/html/index.html

# 프론트엔드 서버 설정
  nginx:
    image: nginx:latest
    container_name: webpage
    restart: always
    volumes:
      - ./webpage:/usr/share/nginx/html

# 백엔드 서버 설정
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    container_name: api
    command: uvicorn main:app --host 0.0.0.0 --port 80
    environment:
      DATABASE_URL: {postgresql://[user]:[password]@db/[db name]}
      MINIO_ENDPOINT: {minio endpoint}
      MINIO_ACCESS_KEY: {minio access key}
      MINIO_SECRET_KEY: {minio secret key}
      MINIO_BUCKET: {minio bucket name}
      XR_WEB_SERVER_GOOGLE_CLIENT_ID: {Google SSO admin ID}
      XR_WEB_SERVER_GOOGLE_CLIENT_SECRET: {Google SSO admin password}
      XR_WEB_SERVER_GOOGLE_REDIRECT_URI: {Login redirection page (domain/auth)}
    depends_on:
      - db

# db 설정
  db:
    image: postgres:latest
    container_name: postgresdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: {db name}
      POSTGRES_USER: {db user}
      POSTGRES_PASSWORD: {db password}

# db 관리도구(Optional)
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5555:80"
    # volumes:
    #   - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL={pgadmin ID}
      - PGADMIN_DEFAULT_PASSWORD={pgadmin password}
      - TZ=Asia/Seoul
    depends_on:
      - db

# 시그널링 서버
  janus:
      build:
        context: ./janus
        dockerfile: Dockerfile
      restart: always
      container_name: janus
      ports:
        - 7088:7088
        - 8088:8088
        - 8188:8188
        - 8989:8989
        - 10000-10030:10000-10030/udp

# SSL 관리 컨테이너
  certbot:
    depends_on:
      - proxy 
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../jsy/certbot:/etc/letsencrypt
      - ./webpage/index.html:/usr/share/nginx/html/index.html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email {your email} --agree-tos --no-eff-email --keep-until-expiring -d {your domain}

# 사설 TURN 서버
  coturn:
    image: coturn/coturn:4.5.2
    container_name: coturnserver
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf