version: "3"

services:
  proxy:
    depends_on:
      - nginx
      - fastapi
      - janus
    image: nginx:alpine
    container_name: proxyserver 
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxyserver/nginx.conf:/etc/nginx/nginx.conf
      - ../jsy/certbot:/etc/letsencrypt
      # - ./webpage:/usr/share/nginx/html
      - ./proxyserver/janus:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: webpage
    restart: always
    volumes:
      - ./webpage:/usr/share/nginx/html

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    container_name: api
    command: uvicorn main:app --host 0.0.0.0 --port 80
    environment:
      DATABASE_URL: postgresql://fastapiuser:fastapipassword@db/fastapidb
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "fastapidb"
      POSTGRES_USER: "fastapiuser"
      POSTGRES_PASSWORD: "fastapipassword"
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5555:80"
    # volumes:
    #   - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - TZ=Asia/Seoul
    depends_on:
      - db

  janus:
      build:
        context: ./janus
        dockerfile: Dockerfile
      restart: always
      container_name: janus
      # volumes:
      #   - ./janus/log/:/var/log/
      ports:
        - 7088:7088
        - 8088:8088
        - 8188:8188
        - 10000-10030:10000-10030/udp

  certbot:
    depends_on:
      - proxy 
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../jsy/certbot:/etc/letsencrypt
      - ./webpage:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email test@test.com --agree-tos --no-eff-email --keep-until-expiring -d rtctest.p-e.kr

  coturn:
    image: coturn/coturn:4.5.2
    container_name: coturnserver
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf