version: "3"

services:
  proxy:
    depends_on:
      - nginx
      - fastapi
      # - janus
    image: nginx:alpine
    container_name: proxyserver 
    restart: always 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxyserver/nginx.conf:/etc/nginx/nginx.conf
      - ../jsy/certbot:/etc/letsencrypt
      - ./webpage:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: webpage
    restart: always
    volumes:
      - ./webpage:/usr/share/nginx/html

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    container_name: api
    command: uvicorn main:app --host 0.0.0.0 --port 80
    environment:
      DATABASE_URL: postgresql://fastapiuser:fastapipassword@db/fastapidb
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresdb
    # volumes:
      # - ./db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "fastapidb"
      POSTGRES_USER: "fastapiuser"
      POSTGRES_PASSWORD: "fastapipassword"
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5555:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - TZ=Asia/Seoul
    depends_on:
      - db

  # janus:
  #   image: 'sucwangsr/janus-webrtc-gateway-docker:1.2.1-slim'
  #   command: /usr/local/bin/janus -F /usr/local/etc/janus   # Janus 이미지
  #   container_name: janusserver
  #   restart: always
  #   volumes:
  #     - "./janus/conf/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"  # open adminapi config
  #     - "./janus/conf/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
  #     - "./janus/conf/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"   # Janus 설정 파일
  #     - "./janus/conf/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg"
  #   ports:
  #     - "8088:8088"  # HTTP API 포트
  #     - "8188:8188"  # WebSocket API 포트
  #     # - "8089:8089"  # HTTPS API 포트 (SSL)
  #     - "10000-10200:10000-10200/udp" # WebRTC 미디어 포트
  #     - "7088:7088"
  #   # depends_on:
  #   #   - nginx    # Nginx 의존성 설정 (옵셔널)

  certbot:
    depends_on:
      - proxy 
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../jsy/certbot:/etc/letsencrypt
      - ./webpage:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email test@test.com --agree-tos --no-eff-email --keep-until-expiring -d rtctest.p-e.kr